image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Puppeteer
    init: yarn install && npm i -g puppeteer
    command: yarn start

  - name: Setup Trigger
    init: cd trigger && deno cache deps.ts

  - name: Setup Getter
    init: cd getter && deno cache deps.ts